3.1.8.1

diff --git a/bin/teamspeak-installer b/bin/teamspeak-installer
--- a/bin/teamspeak-installer
+++ b/bin/teamspeak-installer
@@ -4,7 +4,7 @@
 # an installation package of the TeamSpeak 3 and run the installer
 # Created by Paweł "pavroo" Pijanowski 2017/01/19
 # Copyright 2017-2018 under the GNU GPL2 License
-# Last update 2018/01/25
+# Last update 2018/04/01
 
 DEFLOCDIR="/usr/share/sparky/teamspeak-installer"
 if [ "`cat /etc/default/locale | grep es_AR`" != "" ]; then
@@ -26,7 +26,6 @@ else
 fi
 
 testroot="`whoami`"
-
 if [ "$testroot" != "root" ]; then
 	/usr/bin/remsu $0 &
 fi
@@ -41,10 +40,11 @@ MENU="--list --column=$LOCAL2 --column=$LOCAL3"
 TITLETEXT="$LOCAL4"
 WORKDIR="/tmp/teamspeak"
 ARCH=`uname -r | grep "amd64" | awk '{print $1}'`
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="/usr/bin/sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 SERVER="http://dl.4players.de/ts/releases/3.1.8"
 PACK32="TeamSpeak3-Client-linux_x86-3.1.8.run"
@@ -103,9 +103,9 @@ else
 	cd $WORKDIR
 
 	if [ "$ARCH" = "" ]; then
-		$SPARKYXTERM -e wget $SERVER/$PACK32
+		$SPARKYXTERM "wget $SERVER/$PACK32"
 	else
-		$SPARKYXTERM -e wget $SERVER/$PACK64
+		$SPARKYXTERM "wget $SERVER/$PACK64"
 	fi
 
 	# install teamspeak
@@ -114,7 +114,7 @@ else
 	if [ -f $WORKDIR/*.run ]; then
 		cd $WORKDIR
 		chmod +x *.run
-		$SPARKYXTERM -e sh $PACKTEST
+		$SPARKYXTERM "sh $PACKTEST"
 	fi
 	
 	if [ "$ARCH" = "" ]; then
@@ -194,9 +194,9 @@ if [ -f /usr/bin/teamspeak3 ]; then
 		cd $WORKDIR
 
 		if [ "$ARCH" = "" ]; then
-			$SPARKYXTERM -e wget $SERVER/$PACK32
+			$SPARKYXTERM "wget $SERVER/$PACK32"
 		else
-			$SPARKYXTERM -e wget $SERVER/$PACK64
+			$SPARKYXTERM "wget $SERVER/$PACK64"
 		fi
 
 		PACKTEST=`ls $WORKDIR | grep 'run' | awk '{print $1}'`
@@ -233,7 +233,7 @@ if [ -f /usr/bin/teamspeak3 ]; then
 		PACKTEST=`ls $WORKDIR | grep 'run' | awk '{print $1}'`
 		cd $WORKDIR
 		chmod +x *.run
-		$SPARKYXTERM -e sh $PACKTEST
+		$SPARKYXTERM "sh $PACKTEST"
 			
 		if [ "$ARCH" = "" ]; then
 			if [ -d $WORKDIR/TeamSpeak3-Client-linux_x86 ]; then
@@ -325,7 +325,6 @@ else
 fi
 
 mainmenu
-
 }
 
 mainmenu
